server:
  port: 8089

spring:
#  application:
#    name: mysql-cluster
  profiles:
    active: dev
#  datasource:
#    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
#    url: jdbc:shardingsphere:classpath:sharding-all.yaml

#spring:
#  profiles:
#    active: dev
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 123456
#    url: jdbc:mysql://192.168.1.116:3306/test_db?serverTimezone=Asia/Shanghai
